import { AppProps } from 'next/app';
import Head from 'next/head';
import { GlobalStyles } from 'styles/global';

const App = ({ Component, pageProps }: AppProps) => {
	return (
		<>
			<Head>
				<title>Boilerplate</title>
				<link rel="shortcut" href="/img/favicon.ico" />
				<meta name="description" content="Generated by create next app" />
			</Head>
			<GlobalStyles />
			<Component {...pageProps} />
		</>
	);
};

export default App;
